### ISSUE TITLE
Config Parser Error

### ISSUE THREAD

**Issue by Goro2030** [odudex/bitcoinBeer#2]
Hi! I'm using all the latest versions, and added the btcpayserver approach .... using pip install btcpayserver . 

But unrelated to that, I'm getting a strange error with the config file parsing:

```
Error: subsection not found
Traceback (most recent call last):
  File "C:\Python311\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\silva\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\silva\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\silva\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\silva\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\silva\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\silva\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "C:\Development\bitcoinBeer\RaspberryGUI\main.py", line 212, in <module>
    Config.ConfigWindow.get_config()
  File "C:\Development\bitcoinBeer\RaspberryGUI\Config.py", line 51, in get_config
    beer_name = config.get('beer', 'name')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\configparser.py", line 796, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\configparser.py", line 1167, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'beer'
```

**Comment by odudex** [comment]
Do you have the config.beer file on your folder? It seems it was not loaded.
Notice there's no code to detect  the lack of config file and and a wizard to create a new one. A lot of things could be improved.
